update(readme): update the readme for updraft
Cyfrin/security-and-auditing-full-course-s23 pull request #9
Opened 2023-12-07 21:35 UTC by cromewar

2023-12-07 21:40 UTC, PatrickAlphaC requested changes

2023-12-07 21:40 UTC, PatrickAlphaC commented on README.md
> +Join our vibrant community on various platforms and stay updated with the latest from Cyfrin Updraft:
```suggestion
Join our community on various platforms and stay updated with the latest from Cyfrin Updraft:
```

2024-01-25 12:33 UTC, Mucunguzi256 commented
Quite a good one 

2024-03-07 00:50 UTC, PatrickAlphaC commented
closing due to stale

2024-03-07 00:50 UTC, closed without merging